export const ROUTES = {
  FAVICON: '/favicon.png',
  HTMX: '/htmx.js',
  ADMIN: '/',
  ADMIN_CSS: '/admin.css',
  HEALTH_FRAGMENT: '/health/fragment',
  SIGNAL_INFO_FRAGMENT: '/signal-info/fragment',
  ENDPOINTS_FRAGMENT: '/endpoints/fragment',
  QR_SECTION: '/link/qr-section',
  QR_IMAGE: '/link/qr-image',
  STATUS_CHECK: '/link/status-check',
  MATRIX_NOTIFY: '/_matrix/push/v1/notify',
  UP: '/up',
  UP_INSTANCE: '/up/:instance',
} as const;
